# Generated by Django 5.0 on 2024-02-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfe_app', '0002_addvideomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmodel',
            name='date_created',
            field=models.DateField(auto_now_add=True, default='2024-02-09'),
            preserve_default=False,
        ),
    ]
