# Generated by Django 5.0 on 2024-02-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfe_app', '0003_supportmodel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvideomodel',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
