# Generated by Django 5.0 on 2024-02-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfe_app', '0004_alter_addvideomodel_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addvideomodel',
            name='video',
            field=models.FileField(upload_to='media/'),
        ),
    ]
